version: '3.7'

services:
  db:
    image: centurylink/mysql
    container_name: real_state-db
    # - .data:/var/lib/mysql
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env.docker
    ports:
      - "3306:3306"

  app:
    build: .
    command: ./scripts/start
    container_name: real_state-app
    image: real_state:1.0
    ports:
      - 3000:3000
    env_file:
      - .env.docker
    depends_on:
      - db
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
    tty: true
    stdin_open: true

volumes:
  db_data:
  gem_cache:
